#include "parameter.h"

int FRAME_WIDTH = 640;
int FRAME_HEIGHT = 480;
int BEV_WIDTH = 720;
int BEV_HEIGHT = 960;
int CAR_WIDTH = 240;
int CAR_HEIGHT = 320;
float FOCAL_SCALE = 1.5f;
float SIZE_SCALE = 2.0f;


int SHIFT_WIDTH = 0;
int SHIFT_HEIGHT = 60;

int INNER_SHIFT_WIDTH = 60;
int INNER_SHIFT_HEIGHT = 80;

int TOTAL_WIDTH = 720 + 2 * SHIFT_WIDTH;
int TOTAL_HEIGHT = 840+ 2 * SHIFT_HEIGHT;

int CAR_LEFT = SHIFT_WIDTH + 180 + INNER_SHIFT_WIDTH;
int CAR_RIGHT = TOTAL_WIDTH - CAR_LEFT;
int CAR_TOP = SHIFT_HEIGHT + 180 + INNER_SHIFT_HEIGHT;
int CAR_BOTTOM = TOTAL_HEIGHT - CAR_TOP;

int PROJECT_SHAPES[4][2] = {
    {TOTAL_WIDTH, CAR_TOP},
    {TOTAL_WIDTH, CAR_TOP},
    {TOTAL_HEIGHT, CAR_LEFT},
    {TOTAL_HEIGHT, CAR_LEFT}
};